/**
 * Comprehensive MSCI Level 4 Industry to OECD ICIO Sector Mapping
 * Total: 219 industries mapped to 45 OECD codes
 * Source: ISIN-Based API Integration Guide
 * Validated: All codes confirmed by Supply Chain Risk API
 */

export const COMPREHENSIVE_SECTOR_MAPPING: Record<string, string> = {
  'Aerospace': 'C302T309',
  'Aerospace & Defense': 'C302T309',
  'Airlines': 'H51',
  'Alt. Electricity': 'D',
  'Alternative Energy': 'C27',
  'Alternative Fuels': 'C19',
  'Aluminum': 'C24B',
  'Apparel Retailers': 'G',
  'Asset Mngr, Custodian': 'K',
  'Auto Parts': 'C29',
  'Auto Services': 'C29',
  'Automobiles': 'C29',
  'Automobiles & Parts': 'C29',
  'Banks': 'K',
  'Basic Materials': 'C20',
  'Basic Resources': 'B07',
  'Beverages': 'C10T12',
  'Biotechnology': 'C21',
  'Bldg Materials: Other': 'C23',
  'Bldg: Climate Control': 'C27',
  'Brewers': 'C10T12',
  'Building & Plumbing': 'C23',
  'Cable TV Services': 'J61',
  'Casinos & Gambling': 'R',
  'Cement': 'C23',
  'Chem. & Syn. Fibers': 'C13T15',
  'Chemicals': 'C20',
  'Chemicals: Divers.': 'C20',
  'Closed End Invest.': 'K',
  'Clothing, Accessories': 'C13T15',
  'Coal': 'B05',
  'Comm. Vehicles, Lease': 'C29',
  'Comm. Vehicles, Parts': 'C29',
  'Computer Hardware': 'C26',
  'Computer Services': 'J62_63',
  'Construction': 'F',
  'Construction & Mats': 'F',
  'Consumer Digital Svs': 'J62_63',
  'Consumer Discretion': 'G',
  'Consumer Electronics': 'J62_63',
  'Consumer Lending': 'K',
  'Consumer Prod & Svs': 'G',
  'Consumer Services': 'S',
  'Consumer Staples': 'C10T12',
  'Consumer Svs: Misc.': 'S',
  'Containers & Package': 'C17_18',
  'Conv. Electricity': 'D',
  'Copper': 'C24B',
  'Cosmetics': 'C31T33',
  'Defense': 'C302T309',
  'Delivery Services': 'H53',
  'Distillers & Vintners': 'C10T12',
  'Div. Fin. Services': 'K',
  'Divers. Industrials': 'C28',
  'Diversified Materials': 'C20',
  'Diversified REITs': 'L',
  'Diversified Retailers': 'G',
  'Drug & Grocery Stores': 'G',
  'Drug Retailers': 'G',
  'Education Services': 'P',
  'Elec. & Electrical Eq': 'C27',
  'Elec. Entertainment': 'J58T60',
  'Elec. Eq: Control': 'C27',
  'Elec. Eq: Gauges': 'C27',
  'Elec. Eq: Other': 'C27',
  'Elec. Eq: Pollution': 'C27',
  'Electrical Components': 'C27',
  'Electricity': 'D',
  'Electronic Components': 'C26',
  'Electronic Office Eq.': 'C26',
  'Energy': 'B06',
  'Eng. & Contract Svs': 'F',
  'Entertainment': 'J58T60',
  'Farming, Fishing': 'A01',
  'Fertilizers': 'C20',
  'Fin. Data Providers': 'K',
  'Finance & Credit Svs': 'K',
  'Financial Services': 'K',
  'Financials': 'K',
  'Food Producers': 'C10T12',
  'Food Products': 'C10T12',
  'Food Retail & Wsale': 'G',
  'Food, Bev. and Tobacc': 'C10T12',
  'Footwear': 'C13T15',
  'Forestry': 'A02',
  'Forms & Bulk Print': 'C17_18',
  'Fruit & Grain Proc.': 'C10T12',
  'Full Line Insurance': 'K',
  'Gas Distribution': 'D',
  'Gas, Water & Mul Util': 'D',
  'General Industrials': 'C28',
  'General Mining': 'B07',
  'Glass': 'C23',
  'Gold Mining': 'B07',
  'Health Care': 'Q',
  'Health Care Facility': 'Q',
  'Health Care Mgmt. Svs': 'Q',
  'Health Care Providers': 'Q',
  'Health Care REITs': 'L',
  'Health Care Services': 'Q',
  'Hhold Equip. Products': 'C31T33',
  'Hhold Gds & Home Con.': 'C31T33',
  'Home Construction': 'F',
  'Home Imprv. Retailers': 'G',
  'Hotel & Lodging REITs': 'L',
  'Hotels & Motels': 'I',
  'Household Appliance': 'C27',
  'Household Furnishings': 'C31T33',
  'Ind. Engineering': 'C28',
  'Ind. Goods & Services': 'C28',
  'Ind. Metals & Mining': 'B07',
  'Ind. Support Services': 'N',
  'Ind. Transportation': 'H49',
  'Industrial Materials': 'C20',
  'Industrial REITs': 'L',
  'Industrial Suppliers': 'C28',
  'Industrials': 'C28',
  'Infrastructure REITs': 'L',
  'Insurance': 'K',
  'Insurance Brokers': 'K',
  'Integrated Oil & Gas': 'B06',
  'Inv. Banking & Broker': 'K',
  'Investment Services': 'K',
  'Iron & Steel': 'C24A',
  'Leisure Goods': 'C31T33',
  'Life Insurance': 'K',
  'Luxury Items': 'C31T33',
  'Machinery: Agri.': 'C28',
  'Machinery: Const.': 'C28',
  'Machinery: Engines': 'C28',
  'Machinery: Industrial': 'C28',
  'Machinery: Specialty': 'C28',
  'Machinery: Tools': 'C28',
  'Marine Transportation': 'H50',
  'Media': 'J58T60',
  'Media Agencies': 'J58T60',
  'Medical Eq. Services': 'C26',
  'Medical Equipment': 'C26',
  'Medical Services': 'Q',
  'Medical Supplies': 'C26',
  'Metal Fabricating': 'C25',
  'Mge REITs: Resid.': 'L',
  'Mortgage Finance': 'K',
  'Mortgage REITs': 'L',
  'Multi-Utilities': 'D',
  'NA': 'G',
  'Non-life Insurance': 'K',
  'Nondur.Household Prod': 'C31T33',
  'Nonferrous Metals': 'C24B',
  'Office REITs': 'L',
  'Offshore Drill & Svs': 'B09',
  'Oil Equipment & Svs': 'C28',
  'Oil Refining & Mkting': 'C19',
  'Oil, Gas and Coal': 'B06',
  'Oil: Crude Producers': 'B06',
  'Other Specialty REITs': 'L',
  'Paints & Coatings': 'C20',
  'Paper': 'C17_18',
  'Personal Goods': 'C31T33',
  'Personal Products': 'C31T33',
  'Pharm. & Biotech': 'C21',
  'Pharmaceuticals': 'C21',
  'Pipelines': 'C19',
  'Plastics': 'C22',
  'Plat.& Precious Metal': 'B07',
  'Prec. Metals & Mining': 'B07',
  'Prod. Tech. Equipment': 'C26',
  'Prof.Business Support': 'M',
  'Prop. & Casualty Ins.': 'K',
  'Public administration and defence': 'O',
  'Publishing': 'J58T60',
  'REITs': 'L',
  'Radio TV Broadcasters': 'J58T60',
  'Railroad Equipment': 'C302T309',
  'Railroads': 'H49',
  'Real Estate': 'L',
  'Real Estate Hold, Dev': 'L',
  'Real Estate Inv & Svs': 'L',
  'Real Estate Services': 'L',
  'Recreational Products': 'C31T33',
  'Recreational Services': 'R',
  'Recreational Vehicles': 'C302T309',
  'Reinsurance': 'K',
  'Renewable Energy Eq.': 'C27',
  'Rent & Lease:Consumer': 'S',
  'Residential REITs': 'L',
  'Restaurants & Bars': 'I',
  'Retail REITs': 'L',
  'Retailers': 'G',
  'Rubber and plastics products': 'C22',
  'Security Services': 'N',
  'Semiconductors': 'C26',
  'Soft Drinks': 'C10T12',
  'Software': 'J62_63',
  'Software & Comp. Svs.': 'J62_63',
  'Specialty Chemicals': 'C20',
  'Specialty Retailers': 'G',
  'Storage REITs': 'L',
  'Tech. Hardware, Equip': 'C26',
  'Technology': 'C26',
  'Telecom. Equipment': 'C26',
  'Telecom. Services': 'J61',
  'Telecom. Svs. Prvds.': 'J61',
  'Telecommunications': 'J61',
  'Timber REITs': 'L',
  'Tires': 'C22',
  'Tobacco': 'C10T12',
  'Toys': 'C31T33',
  'Training, Emp. Agency': 'N',
  'Transaction Process': 'C28',
  'Transport Services': 'H49',
  'Travel & Leisure': 'I',
  'Travel & Tourism': 'I',
  'Trucking': 'H49',
  'Utilities': 'D',
  'Vending & Catering': 'G',
  'Warehousing and support activities': 'H52',
  'Waste & Disposal Svs': 'E',
  'Water': 'E'
};

/**
 * Get OECD sector code for an MSCI industry
 * @param industry MSCI Level 4 industry name
 * @returns OECD ICIO sector code or undefined if not found
 */
export function getOECDSectorCode(industry: string): string | undefined {
  return COMPREHENSIVE_SECTOR_MAPPING[industry];
}
